spring:
  datasource:
    url: jdbc:mysql://mysql.im.test:3306/haoke?characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: huke123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  application:
    name: ruijiTakeOut
  flyway:
    enabled: false
    encoding: UTF-8
    locations: classpath:db/migration
    sqlMigrationPrefix: V
    sqlMigrationSeparator: __
    validateOnMigrate: true
    baselineOnMigrate: true

  redis:
    username: root
    password:
    database: 0
    host: localhost
    port: 6379
mybatis-plus:
  configuration: #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
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
server:
  port: 8080
aliyun:
  secret: ${ALIYUN_SECRET}
  accessKeyId: ${ALIYUN_ACCESSKEYID}}